### ISSUE TITLE
error rc=-2 when trying to connect to mqtt broker

### ISSUE THREAD

**Issue by falco9017** [CurlyWurly-1/ESP8266-WIFIMANAGER-MQTT#1]
Hi,
I'm really struggling making this work.
What happens is that, if I connect through my sketch and not using WifiManager, everything goes smooth and I get connected to the broker. Instead if I use WifiManager I am connecting to the wifi but, when then I try connecting to the MQTT broker (cloudmqtt), I keep on getting the same error (rc=-2).
I've looked everywhere but can't find a way to debug this.
Does someone has a clue on this?
Thanks

**Comment by apanasara** [comment]
check following
1. firewall settings
2. MQTT protocol version supported by client as well as broker
